name: Nuget Library Release
description: Composite action that releases on Nuget one or more Nuget libraries from a directory, using a given .NET version.

branding:
  color: green
  icon: tag

inputs:
  dotnet-version:
    description: .NET version to be used (e.g. 5.x or 5.0.x).
    required: true
  nuget-api-key:
    description: The Nuget API key.
    required: true
  nuget-url:
    description: Url of the Nuget server (defaults to nuget.org).
    required: false
    default: https://api.nuget.org/v3/index.json
  publish-dir:
    description: Directory containing all packages to push (defaults to the current directory).
    required: false
    default: .

runs:
  using: composite
  steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ inputs.dotnet-version }}
    - name: Nuget Push
      uses: EasyDesk/action-nuget-push@v1
      with:
        nuget-api-key: ${{ inputs.nuget-api-key }}
        nuget-url: ${{ inputs.nuget-url }}
        publish-dir: ${{ inputs.publish-dir }}
